### ISSUE TITLE
Rename Plan

### ISSUE THREAD

**Issue by dooclock** [oxymore-tech/baku#139] opened 2021-02-17 10:03 UTC
**Is your feature request related to a problem? Please describe.**
Plan should have a name and a number

**Describe the solution you'd like**
Rename a plan by clybing on the name.

**Describe alternatives you've considered**

**Additional context**

**Comment by JBGamond** [comment] 2021-03-02 13:02
duplicate of #140

**Closed by JBGamond** 2021-03-02 13:02 UTC
Labels: duplicate, enhancement
